server:
    servlet:
      context-path: /trnsptng
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trnsptng
    username: sharkDevelop
    password: shark891003    
  jpa:
    show-sql: true
        
url:
  trnsptng:
    app-home: /home
    home-admin: ${url.trnsptng.app-home}/admin/
    home-sttics: ${url.trnsptng.app-home}/statics/
    login-agregar: ${url.trnsptng.app-home}/login
    login-consultar: ${url.trnsptng.app-home}/login
    rol-agregar: ${url.trnsptng.app-home}/rol
    rol-consultar: ${url.trnsptng.app-home}/rol
    
