server:
    servlet:
      context-path: /trnsptng
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trnsptng
    username: sharkDevelop
    password: shark891003    
  jpa:
    show-sql: true
        
url:
  trnsptng:
    app-secure: /secure
    app-home: /home
    home-admin: /admin/
    home-statics: /statics/
    login-agregar: /login
    login-consultar: ${url.trnsptng.app-home}/login/{nickname}
    rol-agregar: /rol
    rol-consultar: /rol
    
